### 루틴 신규 생성
POST localhost:8080/routine
Content-Type: application/json
Authorization: Bearer {accessToken}

{
  "content": "인생 똑바로 살아",
  "repeated": [
    true,
    true,
    true,
    true,
    true,
    true,
    true
  ],
  "alarm": true,
  "alarmTime": "08:30",
  "statType": "갓생력"
}

### 루틴 수정
PATCH localhost:8080/routine
Content-Type: application/json
Authorization: Bearer {accessToken}

{
  "alarm": false,
  "content": "테스트 코드 작성하기",
  "repeated": [
    false,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "routineId": 1
}