package com.finale.neulhaerang.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF974067)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD9E5)
val md_theme_light_onPrimaryContainer = Color(0xFF3E0022)
val md_theme_light_secondary = Color(0xFF735761)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9E5)
val md_theme_light_onSecondaryContainer = Color(0xFF2A151E)
val md_theme_light_tertiary = Color(0xFF7E5537)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCC4)
val md_theme_light_onTertiaryContainer = Color(0xFF301400)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A1C)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A1C)
val md_theme_light_surfaceVariant = Color(0xFFF2DEE3)
val md_theme_light_onSurfaceVariant = Color(0xFF514347)
val md_theme_light_outline = Color(0xFF837378)
val md_theme_light_inverseOnSurface = Color(0xFFFAEEF0)
val md_theme_light_inverseSurface = Color(0xFF352F30)
val md_theme_light_inversePrimary = Color(0xFFFFB0CE)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF974067)
val md_theme_light_outlineVariant = Color(0xFFD5C2C7)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB0CE)
val md_theme_dark_onPrimary = Color(0xFF5D1138)
val md_theme_dark_primaryContainer = Color(0xFF79294F)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD9E5)
val md_theme_dark_secondary = Color(0xFFE1BDC9)
val md_theme_dark_onSecondary = Color(0xFF412932)
val md_theme_dark_secondaryContainer = Color(0xFF5A3F49)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9E5)
val md_theme_dark_tertiary = Color(0xFFF1BC96)
val md_theme_dark_onTertiary = Color(0xFF49290E)
val md_theme_dark_tertiaryContainer = Color(0xFF633E22)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCC4)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A1C)
val md_theme_dark_onBackground = Color(0xFFEBE0E2)
val md_theme_dark_surface = Color(0xFF201A1C)
val md_theme_dark_onSurface = Color(0xFFEBE0E2)
val md_theme_dark_surfaceVariant = Color(0xFF514347)
val md_theme_dark_onSurfaceVariant = Color(0xFFD5C2C7)
val md_theme_dark_outline = Color(0xFF9D8C91)
val md_theme_dark_inverseOnSurface = Color(0xFF201A1C)
val md_theme_dark_inverseSurface = Color(0xFFEBE0E2)
val md_theme_dark_inversePrimary = Color(0xFF974067)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB0CE)
val md_theme_dark_outlineVariant = Color(0xFF514347)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFFCADC)
